language: ruby

env:
  global:
    - JEKYLL_ENV=production
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script: jekyll build && rm -rf ./_site

deploy:
  provider: rubygems
  api_key: $API_KEY
  on:
    tags: true

sudo: false