url: https://127.0.0.1:80
baseurl: /

# variables
title: Jekyll Win95 Theme UPDATED
description: Jekyll theme inpired on the Win95 UI

# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE", "Gemfile", "Gemfile.lock", "jekyll-theme-windows95.gemspec"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
highlighter: rouge
# excerpt_separator: "\n\n"